version: '3'

services:
 db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'db_poo'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'
 
 alpine:
  build:
   context: .
   dockerfile: Dockerfile-app
  command: "python manage.py runserver 0.0.0.0:8000"
  depends_on:
   - db
  ports:
   - "8000:8000"
  restart: always
